-- Reset all foreign key dependent tables first
TRUNCATE TABLE payments RESTART IDENTITY CASCADE;
TRUNCATE TABLE booking RESTART IDENTITY CASCADE;
TRUNCATE TABLE accommodations RESTART IDENTITY CASCADE;
TRUNCATE TABLE users RESTART IDENTITY CASCADE;
TRUNCATE TABLE roles RESTART IDENTITY CASCADE;
